# These are supported funding model platforms for your repository to help fund open source development.
# Learn more at https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/displaying-a-sponsor-button-in-your-repository

github: # Replace with your GitHub username(s) if you have sponsorship enabled
patreon: # Replace with Patreon username
ko_fi: # Replace with Ko-fi username
liberapay: # Replace with Liberapay username
issuehunt: # Replace with IssueHunt username
otechie: # Replace with Otechie username
custom: # Replace with custom funding URLs
